### ISSUE TITLE
Acquisition tool not starting with plugged camera

### ISSUE THREAD

**Issue by Antorithms** [JARVIS-MoCap/JARVIS-AcquisitionTool#4] opened 2022-07-14 16:18 UTC
Hi,
We have this camera BFSU3-16S2M-cs from FLIR and were trying to set up the jarvis acquisition tool. 
When we don't have any camera connected the tool starts normally but when the camera is plugged the software does not start anymore.
Of note if we launch spinnaker and try to start recording the software fails to grab images or stream. 
Let us know if you have any clue on how to troubleshoot this.

**Comment by JARVIS-MoCap** [comment] 2022-07-20 15:09
Hi,

can you please tell me what operating system you are using and what version of the Spinnaker SDK you have installed? 

Best,
Timo

**Comment by JARVIS-MoCap** [comment] 2022-07-20 15:25
Looking into it some more I think the issue is that the latest build of the AcquisitionTool isn't up to date with the latest Spinnaker SDK. I will try to find a fix for this, but in the meantime installing the Spinnaker SDK version **2.6.0.157** might fix your issue. You can find it in the archive folder here: [https://flir.app.boxcn.net/v/SpinnakerSDK/folder/163957116545](https://flir.app.boxcn.net/v/SpinnakerSDK/folder/163957116545)
If you're on Windows you'll want to download the file called `SpinnakerSDK_FULL_2.6.0.157_x64.exe`.

Please let me know if this helps.

**Comment by JARVIS-MoCap** [comment] 2022-07-21 07:15
Hi again,

thanks again for bringing this up! The issue were some missing library files that made the AcquisitionTool dependend on the exact right version of the Spinnaker SDK installed. It should now be fixed and reinstalling the AcquitionTool from the [Releases Page](https://github.com/JARVIS-MoCap/JARVIS-AcquisitionTool/releases/tag/v1.0) should be all you need to do. (Please make sure to uninstall the old version of the AcquisitionTool before to avoid any conflicts)

Best,
Timo

**Comment by Antorithms** [comment] 2022-07-21 16:34
Hey Timo,
Thanks a lot for your quick feedback. I uninstalled the acquisition tool and reinstalled it from the appropriate installer as you indicated nonetheless now even in absence of the connected camera the tool is not lauching. Let us know what you think ho what could be the problem. 
Thanks once more for your help.

**Comment by JARVIS-MoCap** [comment] 2022-07-21 16:42
Thanks for letting me know, I'll look into it. What operating system are you on?

**Comment by Antorithms** [comment] 2022-07-21 16:43
Windows is the OS! 
Super thanks for the prompt reply.

**Comment by JARVIS-MoCap** [comment] 2022-07-21 17:24
Hi again,

seems like by fixing one issue I created another. It should be fixed now though, hopefully this time for real. 
Could you please reinstall the software one more time, again using the latest version on the releases page?

Thanks for helping me figure this out and please let me know if this helped,
Timo

**Closed** 2022-08-17 06:36 UTC
Labels: bug
